### ISSUE TITLE
Broken due to a GiantBomb API change

### ISSUE THREAD

**Issue by rspeicher** [rspeicher/GiantBomb.bundle#1]
See https://www.giantbomb.com/forums/api-developers-3017/rss-feeds-seem-to-show-different-video-ids-than-th-1859037/.

**Comment by Fontelroy** [comment]
are there any plans to address this.. since the site redesign i don't know how to rename my videos so the plex agent can accurately identify them

**Comment by Delver26** [comment]
This seems to only affect downloads through the RSS feeds, (as they don't expose **'results.id'** from the api)
I've been using the metadata agent with the giant_bomb_cli downloader, and it's still working perfectly with this plex agent (with a few small mods):
[https://github.com/harryr0se/giant_bomb_cli]

I think GB team would need to amend the RSS URL to use **'results.api_detail_url'**, and not **'results.associations.0.api_detail_url'**, which is what I think they're using at the moment?

The only workaround I could think for this would be a tool that scrapes the api for all the videos, and then creates an array of mappings from guid to api_id, for other applications to use, but this seems a bit excessive perhaps!

**Comment by rspeicher** [comment]
The RSS feeds are still broken, but I've fixed this for myself via https://github.com/rspeicher/giantbomb_downloader, so I'm going to close this out.
